trigger:
  batch: true
  branches:
    include: [ staging ]

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: environment
    value: stg
  - name: sentryEnvironment
    value: staging
  - template: templates/variables.yaml

stages:
  - template: templates/deploy-workflow.yaml
