FROM node:20-alpine AS base

FROM base AS builder

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY . .

RUN npm ci && \
    npm run build || true && \
    npm prune --production

FROM base AS prod

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/dist /app/dist

CMD [ "node", "/app/dist/index.js" ]
