version: '3'

dotenv:
  - api/.env
  - ui/.env
  - email/.env

env:
  COMMIT_SHA:
    sh: git rev-parse --short HEAD

vars:
  PROJECT_NAME: giga-dataops-platform_ingestion-portal

tasks:
  default:
    desc: Build and start Docker containers
    cmds:
      - docker compose --project-name giga-dataops-platform --file docker-compose-network.yaml up --detach --build --remove-orphans {{.CLI_ARGS}}
      - docker compose --project-name {{.PROJECT_NAME}} up --detach --build --remove-orphans {{.CLI_ARGS}}

  setup:
    desc: Run first-time setup tasks
    cmds:
      - task: setup-pre-commit
      - task: setup-python
      - task: setup-node

  setup-pre-commit:
    internal: true
    desc: Install pre-commit hooks
    cmds:
      - pip install -U pre-commit
      - pre-commit install --install-hooks -t pre-commit -t commit-msg

  setup-python:
    internal: true
    dir: api
    desc: Install Python dependencies
    cmds:
      - poetry env use 3.11
      - poetry install --no-root

  setup-node:
    internal: true
    dir: ui
    desc: Install Node dependencies
    cmds:
      - npm install -D

  logs:
    desc: Attach to Docker logs
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} stop {{.CLI_ARGS}}

  restart:
    desc: Restart containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} restart {{.CLI_ARGS}}

  exec:
    desc: Run a command in the specified container
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} exec {{.CLI_ARGS}}

  clean:
    desc: Remove containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} down --volumes --remove-orphans {{.CLI_ARGS}}

  test:
    desc: Run unit tests
    dir: api
    cmds:
      - poetry run pytest

  build-and-push:
    desc: Build and push Docker image
    cmds:
      - task: build-cr
      - task: push-cr

  build-cr:
    internal: true
    desc: Build Docker image
    cmds:
      - >
        docker build --tag {{.INGESTION_PORTAL_IMAGE_REPOSITORY}}:{{.COMMIT_SHA}}
        --build-arg "VITE_SENTRY_DSN={{.VITE_SENTRY_DSN}}"
        --build-arg "VITE_AZURE_CLIENT_ID={{.VITE_AZURE_CLIENT_ID}}"
        --build-arg "VITE_AZURE_TENANT_ID={{.VITE_AZURE_TENANT_ID}}"
        --build-arg "VITE_AZURE_TENANT_NAME={{.VITE_AZURE_TENANT_NAME}}"
        --build-arg "VITE_AZURE_SUSI_AUTH_POLICY_NAME={{.VITE_AZURE_SUSI_AUTH_POLICY_NAME}}"
        --build-arg "VITE_AZURE_PASSWORD_RESET_AUTH_POLICY_NAME={{.VITE_AZURE_PASSWORD_RESET_AUTH_POLICY_NAME}}"
        --build-arg "VITE_DATAHUB_URL=https://io-datahub-dev.unitst.org"
        -f Dockerfile.prod .
      - docker build --tag {{.EMAIL_SERVICE_IMAGE_REPOSITORY}}:{{.COMMIT_SHA}} -f ./email/Dockerfile.prod ./email

  push-cr:
    internal: true
    desc: Push Docker image
    cmds:
      - docker push {{.INGESTION_PORTAL_IMAGE_REPOSITORY}}:{{.COMMIT_SHA}}
      - docker push {{.EMAIL_SERVICE_IMAGE_REPOSITORY}}:{{.COMMIT_SHA}}

  helm-up:
    desc: Install/upgrade Helm chart to a K8s cluster running on localhost
    dir: infra
    cmds:
      - helm dependency update ./helm/data-ingestion
      - kubectl apply -f k8s/namespace.yaml
      - kubectl apply -f k8s/configmap.yaml
      - kubectl apply -f k8s/secrets.yaml
      - >
        helm upgrade --install ingestion-portal ./helm/data-ingestion
        --namespace giga-data-ingestion
        --set image.repository={{.INGESTION_PORTAL_IMAGE_REPOSITORY}}
        --set image.tag={{.COMMIT_SHA}}
        --set service.type=LoadBalancer
      - >
        helm upgrade --install email-service ./helm/email-service
        --namespace giga-data-ingestion
        --set image.repository={{.EMAIL_SERVICE_IMAGE_REPOSITORY}}
        --set image.tag={{.COMMIT_SHA}}

  helm-upi:
    desc: Install/upgrade Helm chart to a K8s cluster with configured HTTPS ingress
    dir: infra
    cmds:
      - helm dependency update ./helm/data-ingestion
      - kubectl apply -f k8s/namespace.yaml
      - kubectl apply -f k8s/configmap.yaml
      - kubectl apply -f k8s/secrets.yaml
      - >
        helm upgrade --install ingestion-portal ./helm/data-ingestion
        --namespace giga-data-ingestion
        --set image.repository={{.INGESTION_PORTAL_IMAGE_REPOSITORY}}
        --set image.tag={{.COMMIT_SHA}}
        --set ingress.enabled=true
        --set ingress.annotations=null
        --set ingress.hosts[0].host={{.INGESTION_PORTAL_INGRESS_HOST}}
        --set ingress.hosts[0].paths[0].path=/
        --set ingress.hosts[0].paths[0].pathType=Prefix
      - >
        helm upgrade --install email-service ./helm/email-service
        --namespace giga-data-ingestion
        --set image.repository={{.EMAIL_SERVICE_IMAGE_REPOSITORY}}
        --set image.tag={{.COMMIT_SHA}}

  helm-down:
    desc: Uninstall Helm chart
    dir: infra/helm
    cmds:
      - helm uninstall email-service --namespace giga-data-ingestion
      - helm uninstall ingestion-portal --namespace giga-data-ingestion
      - kubectl delete all --all --namespace giga-data-ingestion
      - kubectl delete pvc --all --namespace giga-data-ingestion

  makemigrations:
    desc: Generate database migrations
    cmds:
      - task exec -- api poetry run alembic revision --autogenerate -m "{{.CLI_ARGS}}"

  migrate:
    desc: Run database migrations
    cmds:
      - task exec -- api poetry run alembic upgrade head

  psql:
    desc: Open a psql shell
    cmds:
      - task exec -- db psql -U {{.POSTGRESQL_USERNAME}} -d {{.POSTGRESQL_DATABASE}}
