jobs:
  - deployment: Deploy
    displayName: Build and push Data Ingestion Portal
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Docker@2
              displayName: Login to container Registry
              inputs:
                command: login
                containerRegistry: $(ACR_SERVICE_CONNECTION)

            - task: Docker@2
              displayName: Build Docker image
              inputs:
                command: build
                repository: giga-ingestion-portal
                dockerfile: $(Build.SourcesDirectory)/Dockerfile.prod
                arguments: >
                  --build-arg "VITE_SENTRY_DSN=$(viteSentryDsn)"
                  --build-arg "VITE_AZURE_CLIENT_ID=$(azureAdClientId)"
                  --build-arg "VITE_AZURE_TENANT_ID=$(azureAdTenantId)"
                  --build-arg "VITE_AZURE_TENANT_NAME=$(azureAdTenantName)"
                  --build-arg "VITE_AZURE_SUSI_AUTH_POLICY_NAME=$(azureAdSusiPolicyName)"
                  --build-arg "VITE_AZURE_PASSWORD_RESET_AUTH_POLICY_NAME=$(azureAdPasswordResetPolicyName)"
                  --build-arg "VITE_DATAHUB_URL=https://io-datahub-$(deployEnv).unitst.org"
                tags: |
                  $(Build.SourceVersion)

            - task: Docker@2
              displayName: Push image to container registry
              inputs:
                command: push
                repository: giga-ingestion-portal
                containerRegistry: $(ACR_SERVICE_CONNECTION)
                tags: |
                  $(Build.SourceVersion)
