stages:
  - stage: CreateConfig
    displayName: Create/update K8s configuration resources
    jobs:
      - template: create-config.yaml

  - stage: BuildAndPushPortal
    dependsOn: [ ]
    displayName: Build and push Ingestion Portal image
    jobs:
      - template: build-and-push-portal.yaml

  - stage: BuildAndPushEmail
    displayName: Build and push email service
    dependsOn: [ ]
    jobs:
      - template: build-and-push-email.yaml

  - stage: Deploy
    displayName: Deploy Data Ingestion
    dependsOn:
      - BuildAndPushPortal
      - BuildAndPushEmail
      - CreateConfig
    jobs:
      - template: helm-deploy.yaml
