jobs:
  - deployment: Deploy
    displayName: Data Ingestion Portal Deployment
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Helm deploy Ingestion Portal
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/data-ingestion"
                releaseName: ingestion-portal
                namespace: $(kubernetesNamespace)
                arguments: >
                  --values "$(Build.SourcesDirectory)/infra/helm/values.override.yaml"
                  --set image.repository="$(containerRegistryName).azurecr.io/giga-ingestion-portal"
                  --set image.tag="$(Build.SourceVersion)"
                  --set ingress.enabled=true
                  --set ingress.hosts[0].host="io-dataingestion-$(deployEnv).unitst.org"
                  --set ingress.hosts[0].paths[0].path="/"
                  --set ingress.hosts[0].paths[0].pathType=Prefix
                  --set envFrom[2].secretRef.name="oi-ingestionportal-secrets-$(deployEnv)"
