jobs:
  - deployment: Deploy
    displayName: Uninstall all Helm charts
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - task: HelmDeploy@0
              displayName: Helm uninstall Ingestion Portal
              inputs:
                namespace: $(kubernetesNamespace)
                command: uninstall
                arguments: ingestion-portal

            - task: HelmDeploy@0
              displayName: Helm uninstall email service
              inputs:
                namespace: $(kubernetesNamespace)
                command: uninstall
                arguments: email-service

            - task: HelmDeploy@0
              displayName: Helm uninstall PostgreSQL
              inputs:
                namespace: $(kubernetesNamespace)
                command: uninstall
                arguments: postgres
