stages:
  - stage: PreCommit
    displayName: Run pre-commit
    jobs:
      - job: PreCommit
        displayName: Run pre-commit
        strategy:
          matrix:
            Python311:
              node.version: '3.11'
        steps:
          - task: UsePythonVersion@0
            displayName: 'Use Python $(node.version)'
            inputs:
              versionSpec: '$(node.version)'

          - script: python -m pip install --upgrade pre-commit
            displayName: Install pre-commit

          - script: pre-commit run --all-files
            displayName: Run pre-commit

  - stage: TestUIBuild
    displayName: Test UI build
    dependsOn: [ ]
    jobs:
      - job: TestUIBuild
        displayName: Test UI build
        steps:
          - task: UseNode@1
            displayName: Use Node 20
            inputs:
              version: '20.x'

          - script: npm ci
            workingDirectory: ui
            displayName: Install packages

          - script: npm run build
            workingDirectory: ui
            displayName: Build UI
