stages:
  - stage: UninstallAll
    displayName: Uninstall all Helm charts
    jobs:
      - template: helm-uninstall.yaml

  - stage: DeleteAll
    displayName: Delete K8s resources in namespace
    jobs:
      - template: delete-resources.yaml

  - stage: BuildAndPushPortal
    displayName: Build and push Ingestion Portal image
    jobs:
      - template: build-and-push-portal.yaml

  - stage: BuildAndPushEmail
    displayName: Build and push email service
    dependsOn: [ DeleteAll ]
    jobs:
      - template: build-and-push-email.yaml

  - stage: CreateConfig
    displayName: Create/update K8s configuration resources
    dependsOn: [ DeleteAll ]
    jobs:
      - template: create-config.yaml

  - stage: Deploy
    displayName: Deploy Data Ingestion
    dependsOn:
      - BuildAndPushPortal
      - BuildAndPushEmail
      - CreateConfig
    jobs:
      - template: deploy.yaml
