import { useMutation } from "@tanstack/react-query";

import { api } from "@/api";
import { DataQualityCheck, UploadResponse } from "@/types/upload";
import { saveFile, savePdfFromBase64 } from "@/utils/download";

export function useDownloadHelpers(
  uploadData: UploadResponse,
  dqResultData?: DataQualityCheck | null,
) {
  const { mutateAsync: downloadFailedRows } = useMutation({
    mutationFn: api.uploads.download_failed_rows,
  });

  const { mutateAsync: downloadPassedRows } = useMutation({
    mutationFn: api.uploads.download_passed_rows,
  });

  const { mutateAsync: getDqReportPdf } = useMutation({
    mutationFn: api.email.getDqReportPdf,
  });

  const { mutateAsync: getDqReportPdfFromAdls } = useMutation({
    mutationFn: api.email.getDqReportPdfFromAdls,
  });

  const { mutateAsync: downloadRawFile } = useMutation({
    mutationFn: api.uploads.download_raw_file,
  });

  const { mutateAsync: downloadDqKit } = useMutation({
    mutationFn: api.uploads.download_dq_kit,
  });

  const { mutateAsync: downloadMap } = useMutation({
    mutationFn: api.uploads.download_map,
  });

  function getDqArtifactParams() {
    const pathParts = uploadData.dq_full_path?.split("/").filter(Boolean) ?? [];

    return {
      dataset: pathParts[1] || `school-${uploadData.dataset}`,
      country_code: pathParts[3] || uploadData.country,
      filename: pathParts[pathParts.length - 1] || "",
    };
  }

  async function handleDownloadFailedRows() {
    const blob = await downloadFailedRows(getDqArtifactParams());

    if (blob) saveFile(blob);
  }

  async function handleDownloadPassedRows() {
    const blob = await downloadPassedRows(getDqArtifactParams());

    if (blob) saveFile(blob);
  }

  async function handleDownloadDqSummary() {
    if (!dqResultData?.dq_summary) return;

    // Prefer the PDF generated by Dagster and stored in ADLS.
    try {
      const blobResponse = await getDqReportPdfFromAdls({
        dataset: uploadData.dataset,
        country: uploadData.country,
        uploadId: uploadData.id,
      });
      if (blobResponse?.data?.size > 0) {
        saveFile(blobResponse);
        return;
      }
    } catch {
      // Generate the PDF on demand below when the stored copy is unavailable.
    }

    const response = await getDqReportPdf({
      email: uploadData.uploader_email,
      props: {
        dataset: uploadData.dataset,
        dataQualityCheck: dqResultData.dq_summary,
        uploadDate: uploadData.created,
        uploadId: uploadData.id,
        country: uploadData.country,
      },
    });

    if (!response.data.pdf || !response.data.filename) {
      throw new Error("The generated data quality report PDF is empty.");
    }

    savePdfFromBase64(response.data.pdf, response.data.filename);
  }

  async function handleDownloadRawFile() {
    // Extract filename from upload_path (e.g., "raw/uploads/school-geolocation/MOZ/filename.csv" -> "filename.csv")
    const pathParts = uploadData.upload_path?.split("/") || [];
    const filename = pathParts[pathParts.length - 1];

    const blob = await downloadRawFile({
      dataset: uploadData.dataset,
      country_code: uploadData.country,
      filename: filename,
    });
    if (blob) saveFile(blob);
  }

  async function handleDownloadDqKit() {
    const blob = await downloadDqKit({ upload_id: uploadData.id });
    if (blob) saveFile(blob);
  }

  async function handleDownloadMap() {
    const blob = await downloadMap({ upload_id: uploadData.id });
    if (blob) saveFile(blob);
  }

  return {
    handleDownloadFailedRows,
    handleDownloadPassedRows,
    handleDownloadDqSummary,
    handleDownloadRawFile,
    handleDownloadDqKit,
    handleDownloadMap,
  };
}
