"""'add file upload column license'

Revision ID: 92088e51ad75
Revises: 3ae4cebfe253
Create Date: 2024-04-04 12:17:10.526697

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92088e51ad75"
down_revision: str | None = "3ae4cebfe253"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file_uploads",
        sa.Column("column_license", sa.JSON(), server_default='"{}"', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_uploads", "column_license")
    # ### end Alembic commands ###
