"""add_unique_user_role_constraint

Revision ID: f005c94f2469
Revises: 13702ac9960b
Create Date: 2024-08-03 16:52:31.020131

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f005c94f2469'
down_revision: str | None = '13702ac9960b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint('_user_role_uc', 'user_role_association_table', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_role_uc', 'user_role_association_table', type_='unique')

    # ### end Alembic commands ###
