"""add_qos_school_list

Revision ID: 33b58825535e
Revises: d0ecb42fa08e
Create Date: 2024-02-21 08:32:49.396244

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33b58825535e"
down_revision: str | None = "d0ecb42fa08e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qos_school_list",
        sa.Column(
            "request_method",
            sa.Enum("POST", "GET", name="requestmethodenum"),
            nullable=False,
        ),
        sa.Column("api_endpoint", sa.String(), nullable=False),
        sa.Column("data_key", sa.String(), nullable=False),
        sa.Column("school_id_key", sa.String(), nullable=False),
        sa.Column("query_parameters", sa.String(), nullable=False),
        sa.Column("request_body", sa.String(), nullable=False),
        sa.Column(
            "authorization_type",
            sa.Enum(
                "BEARER_TOKEN", "BASIC_AUTH", "API_KEY", name="authorizationtypeenum"
            ),
            nullable=False,
        ),
        sa.Column("bearer_auth_bearer_token", sa.String(), nullable=False),
        sa.Column("basic_auth_username", sa.String(), nullable=False),
        sa.Column("basic_auth_password", sa.String(), nullable=False),
        sa.Column("api_auth_api_key", sa.String(), nullable=False),
        sa.Column("api_auth_api_value", sa.String(), nullable=False),
        sa.Column(
            "pagination_type",
            sa.Enum("PAGE_NUMBER", "LIMIT_OFFSET", name="paginationtypeenum"),
            nullable=False,
        ),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("page_size_key", sa.String(), nullable=False),
        sa.Column(
            "send_query_in",
            sa.Enum("BODY", "QUERY_PARAMETERS", "HEADERS", name="sendqueryinenum"),
            nullable=False,
        ),
        sa.Column("page_number_key", sa.String(), nullable=False),
        sa.Column("page_starts_with", sa.Integer(), nullable=False),
        sa.Column("page_offset_key", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "date_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_qos_school_list_id"), "qos_school_list", ["id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_qos_school_list_id"), table_name="qos_school_list")
    op.drop_table("qos_school_list")
    sa.Enum("POST", "GET", name="requestmethodenum").drop(op.get_bind())
    sa.Enum("BEARER_TOKEN", "BASIC_AUTH", "API_KEY", name="authorizationtypeenum").drop(
        op.get_bind()
    )
    sa.Enum("PAGE_NUMBER", "LIMIT_OFFSET", name="paginationtypeenum").drop(
        op.get_bind()
    )
    sa.Enum("BODY", "QUERY_PARAMETERS", "HEADERS", name="sendqueryinenum").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
