"""init deletion requests

Revision ID: 59aabe1df309
Revises: 40db295f0ae5
Create Date: 2024-05-12 17:17:03.713605

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59aabe1df309"
down_revision: str | None = "40db295f0ae5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletion_requests",
        sa.Column("requested_by_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("requested_by_email", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "requested_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("country", sa.VARCHAR(length=3), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deletion_requests_id"), "deletion_requests", ["id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deletion_requests_id"), table_name="deletion_requests")
    op.drop_table("deletion_requests")
    # ### end Alembic commands ###
