"""'make column_to_schema, query_parameters, and request_body to JSON'

Revision ID: 8bf9cad4ea8a
Revises: ac33970df7f3
Create Date: 2024-03-11 15:35:43.688028

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bf9cad4ea8a"
down_revision: str | None = "ac33970df7f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "file_uploads",
        "column_to_schema_mapping",
        existing_type=sa.VARCHAR(),
        server_default=None,
    )

    op.execute(
        """
        ALTER TABLE file_uploads
        ALTER COLUMN column_to_schema_mapping
        TYPE json USING column_to_schema_mapping::json
    """
    )

    op.alter_column(
        "file_uploads", "column_to_schema_mapping", server_default=sa.text("'{}'::json")
    )

    ####
    op.alter_column(
        "qos_school_connectivity",
        "query_parameters",
        existing_type=sa.VARCHAR(),
        server_default=None,
    )

    op.execute(
        """
        ALTER TABLE qos_school_connectivity
        ALTER COLUMN query_parameters
        TYPE json USING query_parameters::json
    """
    )

    op.alter_column(
        "qos_school_connectivity",
        "query_parameters",
        server_default=sa.text("'{}'::json"),
    )

    ####
    op.alter_column(
        "qos_school_connectivity",
        "request_body",
        existing_type=sa.VARCHAR(),
        server_default=None,
    )

    op.execute(
        """
        ALTER TABLE qos_school_connectivity
        ALTER COLUMN request_body
        TYPE json USING request_body::json
    """
    )

    op.alter_column(
        "qos_school_connectivity", "request_body", server_default=sa.text("'{}'::json")
    )

    ####
    op.alter_column(
        "qos_school_list",
        "column_to_schema_mapping",
        existing_type=sa.VARCHAR(),
        server_default=None,
    )

    op.execute(
        """
        ALTER TABLE qos_school_list
        ALTER COLUMN column_to_schema_mapping
        TYPE json USING column_to_schema_mapping::json
    """
    )

    op.alter_column(
        "qos_school_list",
        "column_to_schema_mapping",
        server_default=sa.text("'{}'::json"),
    )

    ####
    op.alter_column(
        "qos_school_list",
        "query_parameters",
        existing_type=sa.VARCHAR(),
        server_default=None,
    )

    op.execute(
        """
        ALTER TABLE qos_school_list
        ALTER COLUMN query_parameters
        TYPE json USING query_parameters::json
    """
    )

    op.alter_column(
        "qos_school_list", "query_parameters", server_default=sa.text("'{}'::json")
    )

    ####
    op.alter_column(
        "qos_school_list",
        "request_body",
        existing_type=sa.VARCHAR(),
        server_default=None,
    )

    op.execute(
        """
        ALTER TABLE qos_school_list
        ALTER COLUMN request_body
        TYPE json USING request_body::json
    """
    )

    op.alter_column(
        "qos_school_list", "request_body", server_default=sa.text("'{}'::json")
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file_uploads",
        "column_to_schema_mapping",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        server_default=None,
    )
    op.alter_column(
        "file_uploads", "column_to_schema_mapping", server_default=sa.text("''")
    )
    ####
    op.alter_column(
        "qos_school_list",
        "query_parameters",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        server_default=None,
    )
    op.alter_column("qos_school_list", "query_parameters", server_default=sa.text("''"))
    ####
    op.alter_column(
        "qos_school_list",
        "column_to_schema_mapping",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        server_default=None,
    )
    op.alter_column(
        "qos_school_list", "column_to_schema_mapping", server_default=sa.text("''")
    )

    ####
    op.alter_column(
        "qos_school_connectivity",
        "request_body",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        server_default=None,
    )
    op.alter_column(
        "qos_school_connectivity", "request_body", server_default=sa.text("''")
    )
    ####
    op.alter_column(
        "qos_school_connectivity",
        "query_parameters",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        server_default=None,
    )
    op.alter_column(
        "qos_school_connectivity", "query_parameters", server_default=sa.text("''")
    )
    ####
    op.alter_column(
        "file_uploads",
        "column_to_schema_mapping",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        server_default=None,
    )
    op.alter_column(
        "file_uploads", "column_to_schema_mapping", server_default=sa.text("''")
    )


# ### end Alembic commands ###
