"""'add status to school_list'

Revision ID: 53de7b5296ee
Revises: 33b58825535e
Create Date: 2024-02-22 07:04:07.780883

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53de7b5296ee"
down_revision: str | None = "33b58825535e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "qos_school_list",
        sa.Column(
            "status", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("qos_school_list", "status")
    # ### end Alembic commands ###
