"""initial migration

Revision ID: 788f584b7a1f
Revises:
Create Date: 2024-02-14 13:52:34.471138

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "788f584b7a1f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_uploads",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uploader_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("uploader_email", sa.String(), nullable=False),
        sa.Column("upload_path", sa.String(), nullable=False),
        sa.Column("dq_report_path", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_uploads_id"), "file_uploads", ["id"], unique=True)
    op.create_index(
        op.f("ix_file_uploads_uploader_id"),
        "file_uploads",
        ["uploader_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_uploads_uploader_id"), table_name="file_uploads")
    op.drop_index(op.f("ix_file_uploads_id"), table_name="file_uploads")
    op.drop_table("file_uploads")
    # ### end Alembic commands ###
