"""'add error_message field to api configuration model'

Revision ID: c023cbaa712c
Revises: 8bf9cad4ea8a
Create Date: 2024-03-12 01:48:01.874072

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c023cbaa712c"
down_revision: str | None = "8bf9cad4ea8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "qos_school_connectivity",
        sa.Column("error_message", sa.String(), nullable=True),
    )
    op.add_column(
        "qos_school_list", sa.Column("error_message", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("qos_school_list", "error_message")
    op.drop_column("qos_school_connectivity", "error_message")
    # ### end Alembic commands ###
