"""add approval_request

Revision ID: 58a38cbd03d0
Revises: fa5a528b0af0
Create Date: 2024-04-19 23:10:49.664960

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58a38cbd03d0"
down_revision: str | None = "fa5a528b0af0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_requests",
        sa.Column("country", sa.VARCHAR(length=3), nullable=False),
        sa.Column("dataset", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("country", "dataset", name="uq_country_dataset"),
    )
    op.create_index(
        op.f("ix_approval_requests_id"), "approval_requests", ["id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approval_requests_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    # ### end Alembic commands ###
