"""'add school connectivity and update school list table and file uploads'

Revision ID: ac33970df7f3
Revises: ba50ac9f577e
Create Date: 2024-03-08 15:02:17.283557

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac33970df7f3"
down_revision: str | None = "ba50ac9f577e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qos_school_connectivity",
        sa.Column("ingestion_frequency", sa.Integer(), nullable=False),
        sa.Column("schema_url", sa.String(), nullable=False),
        sa.Column("school_list_id", sa.String(), nullable=False),
        sa.Column("api_auth_api_key", sa.String(), nullable=True),
        sa.Column("api_auth_api_value", sa.String(), nullable=True),
        sa.Column("api_endpoint", sa.String(), nullable=False),
        sa.Column(
            "authorization_type",
            postgresql.ENUM(name="authorizationtypeenum", create_type=False),
            nullable=False,
        ),
        sa.Column("basic_auth_password", sa.String(), nullable=True),
        sa.Column("basic_auth_username", sa.String(), nullable=True),
        sa.Column("bearer_auth_bearer_token", sa.String(), nullable=True),
        sa.Column("data_key", sa.String(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "date_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("page_number_key", sa.String(), nullable=True),
        sa.Column("page_offset_key", sa.String(), nullable=True),
        sa.Column("page_size_key", sa.String(), nullable=True),
        sa.Column("page_starts_with", sa.Integer(), nullable=True),
        sa.Column(
            "pagination_type",
            postgresql.ENUM(name="paginationtypeenum", create_type=False),
            nullable=False,
        ),
        sa.Column("query_parameters", sa.String(), nullable=True),
        sa.Column("request_body", sa.String(), nullable=True),
        sa.Column(
            "request_method",
            postgresql.ENUM(name="requestmethodenum", create_type=False),
            nullable=False,
        ),
        sa.Column("school_id_key", sa.String(), nullable=False),
        sa.Column(
            "send_query_in",
            postgresql.ENUM(name="sendqueryinenum", create_type=False),
            nullable=False,
        ),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_list_id"],
            ["qos_school_list.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_qos_school_connectivity_id"),
        "qos_school_connectivity",
        ["id"],
        unique=True,
    )
    op.add_column(
        "file_uploads",
        sa.Column(
            "column_to_schema_mapping", sa.String(), server_default="", nullable=False
        ),
    )
    op.add_column(
        "qos_school_list",
        sa.Column(
            "column_to_schema_mapping", sa.String(), server_default="", nullable=False
        ),
    )
    op.add_column(
        "qos_school_list",
        sa.Column("name", sa.String(), server_default="", nullable=False),
    )
    op.alter_column(
        "qos_school_list", "api_auth_api_key", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "qos_school_list",
        "api_auth_api_value",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "qos_school_list",
        "basic_auth_password",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "qos_school_list",
        "basic_auth_username",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "qos_school_list",
        "bearer_auth_bearer_token",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "qos_school_list", "data_key", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "qos_school_list", "page_number_key", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "qos_school_list", "page_offset_key", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "qos_school_list", "page_size_key", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "qos_school_list", "page_starts_with", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "qos_school_list", "query_parameters", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "qos_school_list", "request_body", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "qos_school_list", "size", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "qos_school_list", "size", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "qos_school_list", "request_body", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "qos_school_list",
        "query_parameters",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "qos_school_list",
        "page_starts_with",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "qos_school_list", "page_size_key", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "qos_school_list", "page_offset_key", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "qos_school_list", "page_number_key", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "qos_school_list", "data_key", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "qos_school_list",
        "bearer_auth_bearer_token",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "qos_school_list",
        "basic_auth_username",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "qos_school_list",
        "basic_auth_password",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "qos_school_list",
        "api_auth_api_value",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "qos_school_list",
        "api_auth_api_key",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("qos_school_list", "name")
    op.drop_column("qos_school_list", "column_to_schema_mapping")
    op.drop_column("file_uploads", "column_to_schema_mapping")
    op.drop_index(
        op.f("ix_qos_school_connectivity_id"), table_name="qos_school_connectivity"
    )
    op.drop_table("qos_school_connectivity")
    # ### end Alembic commands ###
