"""ingestion_frequency_to_cron_and_remove_school_id_send_query_in_from_school_list

Revision ID: 2f90b0e32a2c
Revises: 07350dc93287
Create Date: 2024-04-23 20:56:52.723936

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2f90b0e32a2c"
down_revision: str | None = "07350dc93287"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "qos_school_connectivity",
        sa.Column(
            "ingestion_frequency",
            sa.String(),
            nullable=False,
            server_default="*/30 * * * *",
        ),
    )
    op.drop_column("qos_school_connectivity", "ingestion_frequency_minutes")
    op.drop_column("qos_school_list", "school_id_send_query_in")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "qos_school_list",
        sa.Column(
            "school_id_send_query_in",
            postgresql.ENUM("BODY", "QUERY_PARAMETERS", "NONE", name="sendqueryinenum"),
            server_default=sa.text("'QUERY_PARAMETERS'::sendqueryinenum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "qos_school_connectivity",
        sa.Column(
            "ingestion_frequency_minutes",
            sa.INTEGER(),
            server_default=sa.text("10"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("qos_school_connectivity", "ingestion_frequency")
    # ### end Alembic commands ###
