"""'drop tables'

Revision ID: 7f77cd6a7420
Revises: 33b58825535e
Create Date: 2024-03-12 09:55:00.439846

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f77cd6a7420"
down_revision: str | None = "33b58825535e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("DROP TABLE IF EXISTS file_uploads")
    op.execute("DROP TABLE IF EXISTS qos_school_list")
    op.execute("DROP TABLE IF EXISTS qos_school_connectivity")

    op.execute("DROP TYPE IF EXISTS authorizationtypeenum")
    op.execute("DROP TYPE IF EXISTS paginationtypeenum")
    op.execute("DROP TYPE IF EXISTS requestmethodenum")
    op.execute("DROP TYPE IF EXISTS sendqueryinenum")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
