"""'remove HEADERS enum from school list'

Revision ID: f1daf3173765
Revises: 53de7b5296ee
Create Date: 2024-02-28 01:25:34.952112

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1daf3173765"
down_revision: str | None = "53de7b5296ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE temp_enum_type AS ENUM('BODY', 'QUERY_PARAMETERS')")

    op.alter_column(
        "qos_school_list",
        "send_query_in",
        type_=sa.Text(),
        postgresql_using="send_query_in::text",
    )
    op.alter_column(
        "qos_school_list",
        "send_query_in",
        type_=sa.Enum("BODY", "QUERY_PARAMETERS", name="temp_enum_type"),
        postgresql_using="send_query_in::temp_enum_type",
    )

    op.execute("DROP TYPE sendqueryinenum")

    op.execute("ALTER TYPE temp_enum_type RENAME TO sendqueryinenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE temp_enum_type AS ENUM('BODY', 'QUERY_PARAMETERS', 'HEADERS')"
    )

    op.alter_column(
        "qos_school_list",
        "send_query_in",
        type_=sa.Text(),
        postgresql_using="send_query_in::text",
    )
    op.alter_column(
        "qos_school_list",
        "send_query_in",
        type_=sa.Enum("BODY", "QUERY_PARAMETERS", "HEADERS", name="temp_enum_type"),
        postgresql_using="send_query_in::temp_enum_type",
    )

    op.execute("DROP TYPE sendqueryinenum")

    op.execute("ALTER TYPE temp_enum_type RENAME TO sendqueryinenum")

    pass
    # ### end Alembic commands ###
