"""add user name fields

Revision ID: abecb3ed9260
Revises: 203c526ef37f
Create Date: 2024-06-09 14:19:22.626360

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abecb3ed9260"
down_revision: str | None = "203c526ef37f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("given_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("surname", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "surname")
    op.drop_column("users", "given_name")
    # ### end Alembic commands ###
