"""'add name field to school_list'

Revision ID: 6dc6726fea6d
Revises: f1daf3173765
Create Date: 2024-02-28 10:08:22.341920

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dc6726fea6d"
down_revision: str | None = "f1daf3173765"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "qos_school_list",
        sa.Column("name", sa.String(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("qos_school_list", "name")
    # ### end Alembic commands ###
