"""

Revision ID: 49a684bb43f3
Revises: a3c6ab14b3f8
Create Date: 2025-11-27 10:50:01.201361

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '49a684bb43f3'
down_revision: str | None = 'a3c6ab14b3f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('upload_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_approval_requests_upload_id'), 'approval_requests', ['upload_id'], unique=False)
    op.create_foreign_key(None, 'approval_requests', 'file_uploads', ['upload_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'approval_requests', type_='foreignkey')
    op.drop_index(op.f('ix_approval_requests_upload_id'), table_name='approval_requests')
    op.drop_column('approval_requests', 'upload_id')
    # ### end Alembic commands ###
