"""

Revision ID: a3c6ab14b3f9
Revises: f005c94f2469
Create Date: 2025-11-18 07:11:18.057429

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3c6ab14b3f8'
down_revision: str | None = 'f005c94f2469'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('metadata_json_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_uploads', 'metadata_json_path')
    # ### end Alembic commands ###
