"""

Revision ID: a3c6ab14b3f8
Revises: f005c94f2469
Create Date: 2025-11-18 07:11:18.057429

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3c6ab14b3f8'
down_revision: str | None = 'f005c94f2469'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('metadata_json_path', sa.String(), nullable=True))
    op.alter_column('file_uploads', 'dq_full_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'bronze_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'is_processed_in_staging',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('qos_school_connectivity', 'send_date_in',
               existing_type=postgresql.ENUM('BODY', 'QUERY_PARAMETERS', 'NONE', name='senddateinenum'),
               nullable=False,
               existing_server_default=sa.text("'NONE'::senddateinenum"))
    op.alter_column('qos_school_connectivity', 'school_id_giga_govt_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'school_id_giga'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qos_school_connectivity', 'school_id_giga_govt_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'school_id_giga'::text"))
    op.alter_column('qos_school_connectivity', 'send_date_in',
               existing_type=postgresql.ENUM('BODY', 'QUERY_PARAMETERS', 'NONE', name='senddateinenum'),
               nullable=True,
               existing_server_default=sa.text("'NONE'::senddateinenum"))
    op.alter_column('file_uploads', 'is_processed_in_staging',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('file_uploads', 'bronze_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'dq_full_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('file_uploads', 'metadata_json_path')
    # ### end Alembic commands ###
