"""

Revision ID: dbd805443ea0
Revises: 49a684bb43f3
Create Date: 2026-01-19 06:42:48.253126

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dbd805443ea0'
down_revision: str | None = '49a684bb43f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE dqmodeenum AS ENUM ('uploaded', 'master')")
    op.add_column("approval_requests", sa.Column(
        "dq_mode", sa.Enum("uploaded", "master", name="dqmodeenum"),
        nullable=False, server_default="uploaded"
    ))
    op.drop_constraint('uq_country_dataset', 'approval_requests', type_='unique')
    op.create_unique_constraint('uq_country_dataset', 'approval_requests', ['country', 'dataset', 'upload_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_country_dataset', 'approval_requests', type_='unique')
    op.create_unique_constraint('uq_country_dataset', 'approval_requests', ['country', 'dataset'])
    op.drop_column("approval_requests", "dq_mode")
    op.execute("DROP TYPE dqmodeenum")
    # ### end Alembic commands ###
