"""

Revision ID: be0cf0747d5a
Revises: dbd805443ea0
Create Date: 2026-01-19 07:40:25.695605

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be0cf0747d5a'
down_revision: str | None = 'dbd805443ea0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_request_audit_log', sa.Column('dq_mode', sa.Enum('uploaded', 'master', name='dqmodeenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_request_audit_log', 'dq_mode')
    # ### end Alembic commands ###
