"""

Revision ID: 717c037a14cf
Revises: be0cf0747d5a
Create Date: 2026-03-13 08:03:23.418937

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '717c037a14cf'
down_revision: str | None = 'be0cf0747d5a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dq_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('dq_mode', postgresql.ENUM('uploaded', 'master', name='dq_mode'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dagster_run_id', sa.String(), nullable=True),
    sa.Column('result_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['file_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dq_runs_upload_id'), 'dq_runs', ['upload_id'], unique=False)
    op.alter_column('approval_request_audit_log', 'dq_mode',
               existing_type=postgresql.ENUM('uploaded', 'master', name='dqmodeenum'),
               nullable=False)
    op.alter_column('file_uploads', 'dq_full_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'bronze_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'is_processed_in_staging',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('qos_school_connectivity', 'send_date_in',
               existing_type=postgresql.ENUM('BODY', 'QUERY_PARAMETERS', 'NONE', name='senddateinenum'),
               nullable=False,
               existing_server_default=sa.text("'NONE'::senddateinenum"))
    op.alter_column('qos_school_connectivity', 'school_id_giga_govt_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'school_id_giga'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qos_school_connectivity', 'school_id_giga_govt_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'school_id_giga'::text"))
    op.alter_column('qos_school_connectivity', 'send_date_in',
               existing_type=postgresql.ENUM('BODY', 'QUERY_PARAMETERS', 'NONE', name='senddateinenum'),
               nullable=True,
               existing_server_default=sa.text("'NONE'::senddateinenum"))
    op.alter_column('file_uploads', 'is_processed_in_staging',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('file_uploads', 'bronze_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'dq_full_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('approval_request_audit_log', 'dq_mode',
               existing_type=postgresql.ENUM('uploaded', 'master', name='dqmodeenum'),
               nullable=True)
    op.drop_index(op.f('ix_dq_runs_upload_id'), table_name='dq_runs')
    op.drop_table('dq_runs')
    # ### end Alembic commands ###
