"""

Revision ID: 7b89fb20822f
Revises: 49a684bb43f3
Create Date: 2026-03-30 12:01:25.183717

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b89fb20822f'
down_revision: str | None = '49a684bb43f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dq_mode') THEN CREATE TYPE dq_mode AS ENUM ('uploaded', 'master'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dqmodeenum') THEN CREATE TYPE dqmodeenum AS ENUM ('uploaded', 'master'); END IF; END $$;")

    op.create_table('dq_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('dq_mode', postgresql.ENUM('uploaded', 'master', name='dq_mode', create_type=False), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dagster_run_id', sa.String(), nullable=True),
    sa.Column('result_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['file_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dq_runs_upload_id'), 'dq_runs', ['upload_id'], unique=False)
    op.add_column('approval_request_audit_log', sa.Column('dq_mode', sa.Enum('uploaded', 'master', name='dqmodeenum', create_type=False), nullable=False))
    op.add_column('approval_requests', sa.Column('dq_mode', sa.Enum('uploaded', 'master', name='dqmodeenum', create_type=False), nullable=False))
    op.drop_constraint(op.f('uq_country_dataset'), 'approval_requests', type_='unique')
    op.create_unique_constraint('uq_country_dataset', 'approval_requests', ['country', 'dataset', 'upload_id'])
    op.alter_column('file_uploads', 'dq_full_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'bronze_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'is_processed_in_staging',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('qos_school_connectivity', 'send_date_in',
               existing_type=postgresql.ENUM('BODY', 'QUERY_PARAMETERS', 'NONE', name='senddateinenum'),
               nullable=False,
               existing_server_default=sa.text("'NONE'::senddateinenum"))
    op.alter_column('qos_school_connectivity', 'school_id_giga_govt_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'school_id_giga'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qos_school_connectivity', 'school_id_giga_govt_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'school_id_giga'::text"))
    op.alter_column('qos_school_connectivity', 'send_date_in',
               existing_type=postgresql.ENUM('BODY', 'QUERY_PARAMETERS', 'NONE', name='senddateinenum'),
               nullable=True,
               existing_server_default=sa.text("'NONE'::senddateinenum"))
    op.alter_column('file_uploads', 'is_processed_in_staging',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('file_uploads', 'bronze_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'dq_full_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_country_dataset', 'approval_requests', type_='unique')
    op.create_unique_constraint(op.f('uq_country_dataset'), 'approval_requests', ['country', 'dataset'], postgresql_nulls_not_distinct=False)
    op.drop_column('approval_requests', 'dq_mode')
    op.drop_column('approval_request_audit_log', 'dq_mode')
    op.drop_index(op.f('ix_dq_runs_upload_id'), table_name='dq_runs')
    op.drop_table('dq_runs')
    # ### end Alembic commands ###
