"""'add is_archived and archived_at to file_uploads'

Revision ID: 7fb34936ec72
Revises: a3c6ab14b3f8
Create Date: 2026-03-13 13:58:43.995361

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7fb34936ec72'
down_revision: str | None = 'a3c6ab14b3f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('file_uploads', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_uploads', 'archived_at')
    op.drop_column('file_uploads', 'is_archived')
    # ### end Alembic commands ###
