"""

Revision ID: 717c037a14cf
Revises: be0cf0747d5a
Create Date: 2026-03-13 08:03:23.418937

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '717c037a14cf'
down_revision: str | None = 'be0cf0747d5a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dq_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('dq_mode', postgresql.ENUM('uploaded', 'master', name='dq_mode'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dagster_run_id', sa.String(), nullable=True),
    sa.Column('result_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['file_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dq_runs_upload_id'), 'dq_runs', ['upload_id'], unique=False)
    op.alter_column('approval_request_audit_log', 'dq_mode',
               existing_type=postgresql.ENUM('uploaded', 'master', name='dqmodeenum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_request_audit_log', 'dq_mode',
               existing_type=postgresql.ENUM('uploaded', 'master', name='dqmodeenum'),
               nullable=True)
    op.drop_index(op.f('ix_dq_runs_upload_id'), table_name='dq_runs')
    op.drop_table('dq_runs')
    # ### end Alembic commands ###
