"""'add status to school_list'

Revision ID: 53de7b5296ee
Revises: 33b58825535e
Create Date: 2024-02-22 07:04:07.780883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53de7b5296ee'
down_revision: Union[str, None] = '33b58825535e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qos_school_list', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qos_school_list', 'status')
    # ### end Alembic commands ###
