"""add metadata fields 'for' computed filename

Revision ID: d0ecb42fa08e
Revises: 788f584b7a1f
Create Date: 2024-02-14 14:32:11.786928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ecb42fa08e'
down_revision: Union[str, None] = '788f584b7a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('country', sa.VARCHAR(length=3), nullable=False))
    op.add_column('file_uploads', sa.Column('dataset', sa.String(), nullable=False))
    op.add_column('file_uploads', sa.Column('source', sa.String(), nullable=True))
    op.add_column('file_uploads', sa.Column('original_filename', sa.String(), nullable=False))
    op.drop_column('file_uploads', 'upload_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('upload_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('file_uploads', 'original_filename')
    op.drop_column('file_uploads', 'source')
    op.drop_column('file_uploads', 'dataset')
    op.drop_column('file_uploads', 'country')
    # ### end Alembic commands ###
